# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0075_remove_station_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCruiseDataContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postcruisedatacontact',
            unique_together=set([('person', 'project')]),
        ),
    ]
