# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-28 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcruisedatacontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
