# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_administration', '0002_postcruisedatacontact_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcruisedatacontact',
            name='system_user_created',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
