# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161222_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='child_devices',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='parent_device', chained_model_field='possible_parents', help_text='Choose any devices that are attached to your instrument', to='main.ChildDevice', verbose_name='Attached devices'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent_device',
            field=models.ForeignKey(help_text='Choose the instrument or method used for sampling', on_delete=django.db.models.deletion.CASCADE, related_name='parent_device_event', to='main.ParentDevice', verbose_name='Sampling method'),
        ),
        migrations.AlterField(
            model_name='event',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Only choose a station name where the ship has stopped', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Station'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='position_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PositionSource'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='time_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TimeSource'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
