# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161222_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaction',
            name='description',
            field=models.ForeignKey(help_text='Select the description that describes the event action', on_delete=django.db.models.deletion.CASCADE, to='main.EventActionDescription', verbose_name='Description of event action'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='event',
            field=models.ForeignKey(help_text='Select the event from the list for which you want to enter an action.', on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='time',
            field=models.DateTimeField(help_text='TIME IN UTC', verbose_name='Time of event action (UTC)'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='type',
            field=models.CharField(choices=[('TBEGNS', 'Begins'), ('TENDS', 'Ends'), ('TINSTANT', 'Instant')], help_text='Select the description of the time that you are entering', max_length=255, verbose_name='Time description'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='TIME IN UTC', null=True, verbose_name='End time (UTC)'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='start_time',
            field=models.DateTimeField(help_text='TIME IN UTC', verbose_name='Start time (UTC)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='arrival_time',
            field=models.DateTimeField(blank=True, help_text='TIME IN UTC', null=True, verbose_name='Arrival time (UTC)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='departure_time',
            field=models.DateTimeField(blank=True, help_text='TIME IN UTC', null=True, verbose_name='Departure time (UTC)'),
        ),
    ]
