# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161222_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.BooleanField(default=False, help_text='Tick this box if raw data will be produced DURING this event (not after post-cruise processing).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='fail',
            field=models.BooleanField(default=False, help_text='Tick this box if the deployment or sampling (event) failed.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='samples',
            field=models.BooleanField(default=False, help_text='Tick this box if samples will be collected during this event.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='position_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PositionSource'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='position_uncertainty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PositionUncertainty'),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
