# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_island'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandLandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Island')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
    ]
