# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161227_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='storage',
        ),
        migrations.AddField(
            model_name='event',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Not yet happened', 'Not yet happened'), ('Success', 'Success'), ('Failure', 'Failure'), ('Invalid', 'Invalid')], default='Success', help_text='Select the option that best describes the outcome of the event. If the event did not happen because of weather or a decision to not do it, it should be marked as invalid.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='ace_sample_number',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='crate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='julian_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='leg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Leg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
           name='offloading_port',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='pi_initials',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='project_sample_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='ship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Ship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='position_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_position_time_source', to='main.PositionSource'),
        ),
        migrations.AlterField(
            model_name='station',
            name='time_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_device_time_source', to='main.TimeSource'),
        ),
    ]
