# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161227_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(choices=[('Not yet happened', 'Not yet happened'), ('Success', 'Success'), ('Failure', 'Failure'), ('Invalid', 'Invalid')], default='Success', help_text='Select the option that best describes the outcome of the event. If the event did not happen because of weather or a decision to not do it, it should be marked as invalid.', max_length=20, unique=False),
        ),
    ]
