# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161227_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='leg',
            field=models.ManyToManyField(to='main.Leg'),
        ),
        migrations.AddField(
            model_name='person',
            name='principal_investigator',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
