# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161227_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='leg',
            field=models.ManyToManyField(blank=True, to='main.Leg'),
        ),
    ]
