# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161227_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islandlandings',
            options={'verbose_name_plural': 'Island Landings'},
        ),
    ]
