# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170102_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
