# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_samplecontent_species_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaction',
            name='event',
            field=models.ForeignKey(help_text='Select the event from the list for which you want to enter an action.<br>\n                                               If your event is not in the list check the event\'s outcome: should be success or failure. And check that the event hasn\'t been completed either<br>\n                                               (e.g. it should not have an \'ends\' or \'tinstant\' event action")', on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
