# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170104_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='shortened_name',
            field=models.CharField(default='AT', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='contents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='preservation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Platform'),
        ),
    ]
