# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170106_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platformtype',
            new_name='platform_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='ace_sample_number',
        ),
        migrations.AddField(
            model_name='sample',
            name='expedition_sample_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='leg',
            field=models.ForeignKey(default=main.models.current_active_leg_id, on_delete=django.db.models.deletion.CASCADE, to='main.Leg'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mission',
            field=models.ForeignKey(default=main.models.default_mission_id, on_delete=django.db.models.deletion.CASCADE, to='main.Mission'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ship',
            field=models.ForeignKey(default=main.models.default_ship_id, on_delete=django.db.models.deletion.CASCADE, to='main.Ship'),
        ),
    ]
