# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170107_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='name',
            field=models.CharField(max_length=255),
        ),
       migrations.AlterField(
           model_name='sample',
           name='preservation',
           field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Preservation'),
        ),
    ]
