# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170113_0203'),
    ]

    operations = [
#        migrations.RenameModel(
#            old_name='ParentDevice',
#            new_name='SamplingMethod',
#        ),
        migrations.RenameField(
            model_name='event',
            old_name='parent_device',
            new_name='sampling_method'
        ),
#        migrations.AddField(
#            model_name='event',
#            name='sampling_method',
#            field=models.ForeignKey(default=1, help_text='Choose the instrument or method used for sampling', on_delete=django.db.models.deletion.CASCADE, related_name='sampling_method_event', to='main.SamplingMethod', verbose_name='Sampling method'),
#            preserve_default=False,
#        ),
        migrations.AlterField(
            model_name='event',
            name='child_devices',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='sampling_method', chained_model_field='possible_parents', help_text='Choose any devices that are attached to your instrument', to='main.ChildDevice', verbose_name='Attached devices'),
        ),
    ]
