# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170113_0451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentDevice',
            new_name='SamplingMethod',
        ),
    ]

