# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170113_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('date_imported', models.DateTimeField()),
                ('object_type', models.CharField(help_text='From where this was imported from', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SampleFile',
        ),
        migrations.AddField(
            model_name='sample',
            name='specific_contents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sampling_method',
            field=models.ForeignKey(help_text='Choose the instrument or method used for sampling', on_delete=django.db.models.deletion.CASCADE, related_name='sampling_method_event', to='main.SamplingMethod'),
        ),
        migrations.AddField(
            model_name='event',
            name='imported_from_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ImportedFile'),
        ),
    ]
