# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170115_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='object_type',
            field=models.CharField(help_text='From where this was imported', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='importedfile',
            unique_together=set([('file_name', 'object_type')]),
        ),
    ]
