# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170117_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='outcome',
            field=models.CharField(choices=[('Not yet happened', 'Not yet happened'), ('Success', 'Success'), ('Cancelled', 'Cancelled')], default='Success', help_text='Select the option that best describes the outcome of the event. If the event did not happen because of weather or a decision to not do it, it should be marked as invalid.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(choices=[('Not yet happened', 'Not yet happened'), ('Success', 'Success'), ('Failure', 'Failure'), ('Invalid', 'Invalid')], default='Not yet happened', help_text='Select the option that best describes the outcome of the station. If the event did not happen because of weather or a decision to not do it, it should be marked as invalid.', max_length=20),
        ),
    ]
