# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='position_source',
            field=models.ForeignKey(blank=True, help_text="Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PositionSource'),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='position_uncertainty',
            field=models.ForeignKey(blank=True, help_text="Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PositionUncertainty'),
        ),
    ]
