# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170127_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedstation',
            name='type',
            field=models.CharField(choices=[('Marine', 'Marine'), ('Terrestrial', 'Terrestrial')], max_length=20),
        ),
    ]
