# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_emailoversizenotified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoversizenotified',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
