# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20170204_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='make',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
