# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20170204_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificdevice',
            old_name='possible_parent',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_contact',
        ),
        migrations.RemoveField(
            model_name='device',
            name='leg_used',
        ),
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='device',
            name='project',
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='device_contact',
            field=models.ManyToManyField(help_text='Select the person / people who operated or was responsible for the instrument at some point during the voyage. This does not have to be every user of the instrument, but the main operator(s) for each leg.', to='main.Person'),
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='leg_used',
            field=models.ManyToManyField(help_text='Select the leg(s) on which the device was used.', to='main.Leg'),
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='platform',
            field=models.ManyToManyField(help_text='Select one or more platforms from which the device was operated or deployed.', related_name='possible_platform', to='main.Platform'),
        ),
        migrations.AddField(
            model_name='specificdevice',
            name='project',
            field=models.ManyToManyField(help_text='Select the projects which used the device or got samples / data from its deployments.', to='main.Project'),
        ),
    ]
