# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20170204_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificdevice',
            name='description',
            field=models.TextField(blank=True, help_text='Give a full description of the device which includes some information about what it is used for, how it can be used and any specific details that separate it from similar instruments. If you have a URL about the device, please include it here.', null=True),
        ),
    ]
