# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20170206_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('cannot_change_special', 'Cannot change (special)'),)},
        ),
        migrations.AlterModelOptions(
            name='eventaction',
            options={'permissions': (('cannot_change_special', 'Cannot change (special)'),)},
        ),
        migrations.AddField(
            model_name='samplingmethod',
            name='date_validity_changed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingmethod',
            name='validity',
            field=models.CharField(choices=[('valid', 'valid'), ('redundant', 'redundant')], default='valid', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Format: decimal degrees, i.e. -63.334. Note that south is negative. Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True),
        ),
        migrations.AlterField(
            model_name='eventaction',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Format: decimal degrees, i.e. -145.54. Note that west is negative. Only enter position for terrestrial work. Events at sea will automatically get their position from the ship's GPS.", null=True),
        ),
    ]
