# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20170209_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
