# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20170215_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
