# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_person_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechange',
            name='date_changed_utc',
            field=models.DateField(unique=True),
        ),
    ]
