# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20170219_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
