# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20170222_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('depth', models.FloatField()),
            ],
        ),
    ]
