# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_project_sampling_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeuncertainty',
            name='table_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
