# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_auto_20170305_1922'),
        ('main', '0064_auto_20170303_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='instruments',
            field=models.ManyToManyField(blank=True, help_text='Used to link with GCMD instruments.', to='metadata.Instrument'),
        ),
        migrations.AddField(
            model_name='platform',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='uuid',
            field=models.CharField(default=None, help_text='Used for the Metadata Record', max_length=255),
        ),
    ]
