# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20170305_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCtdToEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ctd_cast_number', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUnderwayToEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_underway_number', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectunderwaytoevent',
            unique_together=set([('project_underway_number', 'event', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectctdtoevent',
            unique_together=set([('project_ctd_cast_number', 'event', 'project')]),
        ),
    ]
