# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20170307_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectctdtoevent',
            name='samples',
            field=models.ManyToManyField(to='main.Sample'),
        ),
        migrations.AddField(
            model_name='projectunderwaytoevent',
            name='samples',
            field=models.ManyToManyField(to='main.Sample'),
        ),
    ]
