# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20170308_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsConsistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CTD', 'CTD'), ('UW', 'UW')], max_length=255)),
                ('thing', models.CharField(max_length=255)),
                ('event_from_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
                ('samples', models.ManyToManyField(to='main.Sample')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectctdtoevent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectctdtoevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='projectctdtoevent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectctdtoevent',
            name='samples',
        ),
        migrations.DeleteModel(
            name='ProjectCtdToEvent',
        ),
        migrations.AlterUniqueTogether(
            name='eventsconsistency',
            unique_together=set([('event_from_sample', 'project', 'type', 'thing')]),
        ),
    ]
