# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20170310_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsConsistencyV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CTD', 'CTD'), ('UW', 'UW')], max_length=255)),
                ('event_from_expedition_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_02', to='main.Event')),
                ('event_from_project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sample')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectunderwaytoevent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectunderwaytoevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='projectunderwaytoevent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectunderwaytoevent',
            name='samples',
        ),
        migrations.DeleteModel(
            name='ProjectUnderwayToEvent',
        ),
    ]
