# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_sample_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact details',
            },
        ),
    ]
