# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurelandQualifierFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=255)),
                ('preferred_label', models.CharField(max_length=255)),
                ('alt_label', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Measureland Qualifier Flags',
            },
        ),
    ]
