# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_measurelandqualifierflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, help_text='Name of station location to help search', max_length=50, null=True),
        ),
    ]
