# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_remove_station_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.ManyToManyField(blank=True, to='main.Leg')),
                ('onboard_role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.OnboardRole')),
            ],
            options={
                'verbose_name_plural': 'People Roles',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='initials',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('name_first', 'name_last', 'project')]),
        ),
        migrations.AddField(
            model_name='personrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='personrole',
            unique_together=set([('person', 'project', 'onboard_role')]),
        ),
    ]
