# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20170822_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrole',
            name='principal_investigator',
            field=models.BooleanField(default=False),
        ),
    ]
