# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_personrole_principal_investigator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrole',
            name='onboard_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OnboardRole'),
        ),
    ]
