# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20170822_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
