# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20170921_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechange',
            name='date_changed_utc',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='timechange',
            unique_together=set([('date_changed_utc', 'date_changed_ship_time')]),
        ),
    ]
