# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20170921_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='event',
        ),
        migrations.RemoveField(
            model_name='data',
            name='project',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
