# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20171003_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mission',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Mission'),
            preserve_default=False,
        ),
    ]
