# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20171003_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='storage_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StorageType'),
        ),
    ]
