# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_sample_storage_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='storage_type',
        ),
    ]
