# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_remove_sample_storage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='storage_type2',
            new_name='storage_type',
        ),
    ]
