# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi_admin', '0001_initial'),
        ('main', '0090_auto_20171004_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mailing_list',
            field=models.ManyToManyField(blank=True, to='spi_admin.MailingList'),
        ),
    ]
