version: '3.5'

services:
  spi-media-gallery:
    image: science-cruise-data-management-docker:0.0.1
    secrets:
      - spi_media_gallery_mysql.conf
    volumes:
      - ./SpiMediaGallery:/code/SpiMediaGallery
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    expose:
      - "8000"

  reverse-proxy:
    image: nginx:1.17
    ports:
      - 1234:1234
    environment:
      - NGINX_PORT=1234
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    links:
      - spi-media-gallery

volumes:
  static_volume: {}

secrets:
  spi_media_gallery_mysql.conf:
    file: ${SPI_MEDIA_GALLERY_MYSQL_CONF_PATH}
