version: '3.5'

services:
  science-cruise-data-management:
    image: science-cruise-data-management-docker:0.0.1
    secrets:
      - science_cruise_data_management_mysql.conf
    volumes:
      - ./ScienceCruiseDataManagement:/code/ScienceCruiseDataManagement
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    expose:
      - "8000"

  reverse-proxy:
    image: nginx:1.17
    ports:
      - 1234:1234
    environment:
      - NGINX_PORT=1234
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    links:
      - science-cruise-data-management 

volumes:
  static_volume: {}

secrets:
  science_cruise_data_management_mysql.conf:
    file: ${SCIENCE_CRUISE_DATA_MANAGEMENT_MYSQL_CONF_PATH}
