version: '3.5'

services:
  science-cruise-data-management:
    image: science-cruise-data-management-docker:0.0.1
    secrets:
      - science_cruise_data_management_mysql.conf
    volumes:
      - ./ScienceCruiseDataManagement:/code/ScienceCruiseDataManagement
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    expose:
      - "8000"
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: science-cruise-data-management.django

  reverse-proxy:
    image: nginx:1.19
    secrets:
      - science_cruise_data_management_htpasswd
    environment:
      - NGINX_PORT=80
      - VIRTUAL_HOST=${SCIENCE_CRUISE_DATA_MANAGEMENT_DOMAIN}
      - LETSENCRYPT_HOST=${SCIENCE_CRUISE_DATA_MANAGEMENT_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/ScienceCruiseDataManagement/staticfiles
    links:
      - science-cruise-data-management 
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: science-cruise-data-management.nginx

  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=scdm
      - MYSQL_USER=${SCDM_DB_USER}
      - MYSQL_PASSWORD=${SCDM_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SCDM_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: scdm.mariadb

volumes:
  static_volume: {}
  database:

secrets:
  science_cruise_data_management_mysql.conf:
    file: ${SCIENCE_CRUISE_DATA_MANAGEMENT_MYSQL_CONF_PATH}
  science_cruise_data_management_htpasswd:
    file: ${SCIENCE_CRUISE_DATA_MANAGEMENT_HTPASSWD}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
