# Generated by Django 2.2 on 2019-05-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_on_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_sample_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('project_sample_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.CharField(max_length=255)),
                ('crate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('offloading_port', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('julian_day', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_contents', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('other_data', django_mysql.models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('leg', models.ForeignKey(default=main.models.current_active_leg_id, on_delete=django.db.models.deletion.CASCADE, to='main.Leg')),
                ('mission', models.ForeignKey(default=main.models.default_mission_id, on_delete=django.db.models.deletion.CASCADE, to='main.Mission')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('preservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Preservation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Ship')),
                ('storage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.StorageType')),
            ],
        ),
    ]
