# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0084_auto_20170921_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwaySampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UnderwaySamplingVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='When',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='underwaysampling',
            name='what',
            field=models.ManyToManyField(to='underway_sampling.UnderwaySamplingVariable'),
        ),
        migrations.AddField(
            model_name='underwaysampling',
            name='when',
            field=models.ManyToManyField(to='underway_sampling.When'),
        ),
    ]
