# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underway_sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwaysamplingvariable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
