# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0084_auto_20170921_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtdBottleTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('niskin', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ctd_cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CtdCast')),
            ],
        ),
        migrations.CreateModel(
            name='CtdSampleVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(blank=True, help_text='Blank if unknown', null=True)),
                ('ctd_bottle_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctd.CtdBottleTrigger')),
            ],
        ),
        migrations.CreateModel(
            name='CtdVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ctdsamplevolume',
            name='ctd_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctd.CtdVariable'),
        ),
        migrations.AlterUniqueTogether(
            name='ctdsamplevolume',
            unique_together=set([('ctd_variable', 'ctd_bottle_trigger')]),
        ),
        migrations.AlterUniqueTogether(
            name='ctdbottletrigger',
            unique_together=set([('ctd_cast', 'depth', 'niskin')]),
        ),
    ]
