# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20170921_1427'),
        ('ctd', '0002_auto_20170921_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdvariable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='ctdvariable',
            unique_together=set([('name', 'principal_investigator')]),
        ),
    ]
