# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctd', '0003_auto_20170922_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdvariable',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
