# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='path',
            new_name='destination_path',
        ),
        migrations.AddField(
            model_name='directory',
            name='source_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
