# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage_management.Directory')),
            ],
            options={
                'verbose_name_plural': 'Directory Updates',
            },
        ),
        migrations.RemoveField(
            model_name='directoryupdates',
            name='directory',
        ),
        migrations.DeleteModel(
            name='DirectoryUpdates',
        ),
    ]
