# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0002_auto_20161231_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoryimportlog',
            options={},
        ),
    ]
