# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0003_auto_20170102_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_date_time',
        ),
        migrations.AlterField(
            model_name='item',
            name='destination_directory',
            field=models.CharField(help_text="Can't start with /, it's a relative path", max_length=255, unique=True),
        ),
    ]
