# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0004_auto_20170103_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_directory',
            field=models.CharField(help_text="If it's a directory make sure that ends with / to avoid creating subdirectories. If it's a file(s) then make sure to not have it so it copies them", max_length=255),
        ),
    ]
