# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0005_auto_20170104_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='destination_directory',
            field=models.CharField(help_text="Can't start with /, it's a relative path", max_length=255),
        ),
    ]
