# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0008_item_source_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_instrument',
            field=models.ManyToManyField(blank=True, help_text='Select the instrument(s) which produced the data in this folder.', to='main.SpecificDevice'),
        ),
    ]
