# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0009_auto_20170206_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipData',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_storage_management.Item')),
            ],
            options={
                'verbose_name_plural': 'Ship data',
            },
            bases=('data_storage_management.item',),
        ),
        migrations.AlterField(
            model_name='item',
            name='source_directory',
            field=models.CharField(blank=True, help_text="If it's a directory make sure that ends with / to avoid creating subdirectories. If it's a file(s) then make sure to not have it so it copies them", max_length=255, null=True),
        ),
    ]
