# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0022_metadataentry_skip_update_distribution_size'),
        ('main', '0063_samplingmethod_directory'),
        ('data_storage_management', '0011_item_path_storage'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='shipdata',
        #    name='item_ptr',
        #),
        migrations.DeleteModel(
            name='ShipData',
        ),
    ]
