# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_management', '0013_remove_item_source_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='backup_disabled',
            field=models.BooleanField(default=False, help_text='To disable backups from this directory'),
        ),
    ]
