# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpggsGpsFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmea_string', models.CharField(max_length=255)),
                ('time', models.FloatField()),
                ('latitude', models.FloatField()),
                ('lat_ns', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('lon_ew', models.CharField(max_length=255)),
                ('fix_quality', models.IntegerField()),
                ('no_satellites', models.IntegerField()),
                ('horiz_dilution_of_position', models.FloatField()),
                ('altitude', models.FloatField()),
                ('altitude_units', models.CharField(max_length=255)),
                ('geoid_height', models.FloatField()),
                ('geoid_height_units', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GpvtgVelocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmea_string', models.CharField(max_length=255)),
                ('time', models.FloatField()),
                ('true_track_deg', models.FloatField()),
                ('magnetic_track_deg', models.FloatField()),
                ('ground_speed_kts', models.FloatField()),
                ('ground_speed_kmh', models.FloatField()),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GpzdaDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmea_string', models.CharField(max_length=255)),
                ('time', models.FloatField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('local_zone_hours', models.IntegerField()),
                ('local_zone_minutes', models.IntegerField()),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
    ]
