# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpggaGpsFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fix_quality', models.PositiveSmallIntegerField()),
                ('number_satellites', models.PositiveSmallIntegerField()),
                ('horiz_dilution_of_position', models.FloatField()),
                ('altitude', models.FloatField()),
                ('altitude_units', models.CharField(max_length=1)),
                ('geoid_height', models.FloatField()),
                ('geoid_height_units', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='GpggsGpsFix',
        ),
        migrations.RemoveField(
            model_name='gpvtgvelocity',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='gpvtgvelocity',
            name='ground_speed_kmh',
        ),
        migrations.RemoveField(
            model_name='gpvtgvelocity',
            name='nmea_string',
        ),
        migrations.RemoveField(
            model_name='gpvtgvelocity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='day',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='month',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='nmea_string',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='time',
        ),
        migrations.RemoveField(
            model_name='gpzdadatetime',
            name='year',
        ),
        migrations.AddField(
            model_name='gpvtgvelocity',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpzdadatetime',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
