# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0002_auto_20161223_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpvtgvelocity',
            options={'verbose_name_plural': 'Gpvtg Velocities'},
        ),
    ]
