# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0004_auto_20161228_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpggagpsfix',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gpvtgvelocity',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gpzdadatetime',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
