# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0006_auto_20161228_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpggagpsfix',
            options={'get_latest_by': 'date_time'},
        ),
    ]
