# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0007_auto_20170102_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('WD2MA1', models.FloatField()),
                ('WD2MM1', models.FloatField()),
                ('WD2MX1', models.FloatField()),
                ('WS2MA1', models.FloatField()),
                ('WS2MM1', models.FloatField()),
                ('WS2MX1', models.FloatField()),
                ('WD10MA1', models.FloatField()),
                ('WD10MM1', models.FloatField()),
                ('WD10MX1', models.FloatField()),
                ('WS10MA1', models.FloatField()),
                ('WS10MM', models.FloatField()),
                ('WS10MX1', models.FloatField()),
                ('WD2MA2', models.FloatField()),
                ('WD2MM2', models.FloatField()),
                ('WD2MX2', models.FloatField()),
                ('WS2MA2', models.FloatField()),
                ('WS2MM2', models.FloatField()),
                ('WS2MX2', models.FloatField()),
                ('WD10MA2', models.FloatField()),
                ('WD10MX2', models.FloatField()),
                ('WD10MM2', models.FloatField()),
                ('WS10MA2', models.FloatField()),
                ('WS10MX2', models.FloatField()),
                ('WS10MM2', models.FloatField()),
                ('VIS', models.FloatField()),
                ('wawa', models.FloatField()),
                ('CL1', models.FloatField()),
                ('CL2', models.FloatField()),
                ('CL3', models.FloatField()),
                ('SC1', models.FloatField()),
                ('SC2', models.FloatField()),
                ('SC3', models.FloatField()),
                ('RH1', models.FloatField()),
                ('TA1', models.FloatField()),
                ('DP1', models.FloatField()),
                ('RH2', models.FloatField()),
                ('TA2', models.FloatField()),
                ('DP2', models.FloatField()),
                ('PA1', models.FloatField()),
                ('PA2', models.FloatField()),
                ('SR1', models.FloatField()),
                ('SR2', models.FloatField()),
                ('SR3', models.FloatField()),
                ('UV1', models.FloatField()),
                ('UV2', models.FloatField()),
                ('cond', models.FloatField()),
                ('salinity', models.FloatField()),
                ('TwTwTw', models.FloatField()),
                ('TIMEDIFF', models.FloatField()),
                ('CLOUDTEXT', models.FloatField()),
                ('VISCODE', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Meterological data',
            },
        ),
    ]
