# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0010_auto_20170109_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpvtgvelocity',
            options={'get_latest_by': 'date_time', 'verbose_name_plural': 'Gpvtg Velocities'},
        ),
        migrations.AlterModelOptions(
            name='metdataall',
            options={'get_latest_by': 'date_time', 'verbose_name_plural': 'Meterological data - full set'},
        ),
        migrations.AlterModelOptions(
            name='metdatawind',
            options={'get_latest_by': 'date_time', 'verbose_name_plural': 'Meterological data - wind'},
        ),
    ]
