# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0012_ferrybox'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferrybox',
            name='fluorimeter',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
