# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0013_ferrybox_fluorimeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferrybox',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
