# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0014_auto_20170212_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferrybox',
            name='oxygen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
