# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0015_ferrybox_oxygen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultibeamRawFileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=300)),
                ('directory', models.CharField(max_length=30)),
                ('swath_data_file', models.CharField(max_length=40)),
                ('file_start_time_iso', models.DateTimeField()),
                ('file_end_time_iso', models.DateTimeField()),
                ('minimum_longitude', models.FloatField()),
                ('maximum_longitude', models.FloatField()),
                ('minimum_latitude', models.FloatField()),
                ('maximum_latitude', models.FloatField()),
                ('minimum_sonar_depth', models.FloatField()),
                ('maximum_sonar_depth', models.FloatField()),
            ],
        ),
    ]
