# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_measurelandqualifierflags'),
        ('ship_data', '0017_auto_20170330_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpggagpsfix',
            name='measureland_qualifer_flags',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MeasurelandQualifierFlags'),
        ),
    ]
