# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0018_gpggagpsfix_measureland_qualifer_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpggagpsfix',
            old_name='measureland_qualifer_flags',
            new_name='measureland_qualifier_flags',
        ),
    ]
