# Generated by Django 2.2 on 2019-08-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_data', '0021_auto_20190808_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metdatawind',
            options={'get_latest_by': 'date_time', 'verbose_name_plural': 'Meteorological data - wind'},
        ),
    ]
