# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-27 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0084_auto_20170921_1427'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_people', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(help_text='Please enter the date on which your activity took place.')),
                ('activity_title', models.TextField(help_text='Please give the title of your outreach activity.')),
                ('activity_description', models.TextField(help_text='Please give a brief description of your activity. Please complete the information in the other fields if there is a suitable space to put it.')),
                ('activity_location_event', models.CharField(blank=True, help_text='Please give the name of the event at which your outreach activity took place, if applicable.', max_length=255, null=True)),
                ('activity_location_event_link', models.TextField(blank=True, help_text='Please give a weblink to the outreach activity if available.', null=True)),
                ('link', models.TextField(blank=True, help_text='Please enter the weblink the outreach material if available. If this is a DOI, please enter it in the Outreach DOI name field.', null=True)),
                ('outreach_doi_name', models.CharField(blank=True, help_text='Please enter the DOI name of the outreach activity if applicable.', max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_location_organisation', models.ManyToManyField(help_text='Please list the organisation(s) at which the outreach activity took place.', to='main.Organisation')),
                ('audience_size', models.ForeignKey(help_text='Please estimate the size of the audience reached by your outreach activity.', on_delete=django.db.models.deletion.CASCADE, to='expedition_reporting.AudienceSize')),
                ('audience_type', models.ManyToManyField(help_text='Please give an idea of the type of audience at which your activity was aimed.', to='expedition_reporting.AudienceType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_type', models.ManyToManyField(help_text='Please select the main types of media used during your outreach activity.', to='expedition_reporting.MediaType')),
                ('person', models.ManyToManyField(help_text='Please enter the people that were involved in your outreach activity. If they are not listed here, please add them to the database.', to='main.Person')),
                ('project', models.ManyToManyField(help_text='Please select the project(s) to which your outreach activity was related. If it was about the expedition in general, please select all projects.', to='main.Project')),
            ],
        ),
    ]
