# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedition_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outreachactivity',
            options={'verbose_name_plural': 'Outreach Activities'},
        ),
    ]
