# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition_reporting', '0004_auto_20170930_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachactivity',
            name='activity_location_organisation',
            field=models.ManyToManyField(blank=True, help_text='Please list the organisation(s) at which the outreach activity took place.', to='main.Organisation'),
        ),
    ]
