# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20170213_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='detailed_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='detailed_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacitecontributortype',
            name='contributor_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='datasetprogress',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetprogress',
            name='type',
            field=models.CharField(default='', max_length=31, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetrole',
            name='role',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='distributionformat',
            name='description',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributionformat',
            name='distribution_format',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='keyword_revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporalresolutionrange',
            name='temporal_resolution_range',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verticalresolutionrange',
            name='vertical_resolution_range',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='distributionmedia',
            unique_together=set([('media_type', 'distribution_media')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('location_category', 'location_type', 'location_subregion1', 'location_subregion2', 'location_subregion3', 'detailed_location')]),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set([('category', 'series_entity', 'short_name', 'long_name', 'detailed_platform', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('bucket', 'short_name', 'long_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set([('bucket_Level0', 'bucket_Level1', 'bucket_Level2', 'bucket_Level3', 'short_name', 'long_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='rucontenttype',
            unique_together=set([('type', 'subtype')]),
        ),
    ]
