# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20170213_2057'),
        ('metadata', '0003_auto_20170213_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idnnode',
            old_name='long_name',
            new_name='idn_node_long_name',
        ),
        migrations.RenameField(
            model_name='idnnode',
            old_name='short_name',
            new_name='idn_node_short_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='idnnode',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idnnode',
            name='idn_node_use_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idnnode',
            name='in_gcmd',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idnnode',
            name='keyword_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idnnode',
            name='keyword_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idnnode',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
