# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20170213_2057'),
        ('data_storage_management', '0010_auto_20170209_0751'),
        ('metadata', '0004_auto_20170213_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataentry',
            name='ace_project',
            field=models.ManyToManyField(to='main.Project'),
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='directory',
            field=models.ManyToManyField(to='data_storage_management.Item'),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='horizontal_resolution_range',
            field=models.ForeignKey(blank=True, help_text='The range should be selected based on the <Latitude_Resolution> and <Longitude_Resolution>.', null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.HorizontalResolutionRange'),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='latitude_resolution',
            field=models.CharField(blank=True, help_text='The minimum difference between two adjacent latitude values.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='longitude_resolution',
            field=models.CharField(blank=True, help_text='The minimum difference between two adjacent longitude values.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='temporal_resolution',
            field=models.CharField(blank=True, help_text='the frequency of data sampled.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='temporal_resolution_range',
            field=models.ForeignKey(blank=True, help_text='The range should be selected based on the specified <Temporal_Resolution>.', null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.TemporalResolutionRange'),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='vertical_resolution',
            field=models.CharField(blank=True, help_text='The minimum difference possible between two adjacent vertical values.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataresolution',
            name='vertical_resolution_range',
            field=models.ForeignKey(blank=True, help_text='The range should be selected based on the specified <Vertical_Resolution>.', null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.VerticalResolutionRange'),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='dataset_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='dataset_title',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='other_citation_details',
            field=models.CharField(blank=True, help_text='Additional free-text citation information.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='horizontalresolutionrange',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='idnnode',
            name='idn_node_long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='data_center',
            field=models.ManyToManyField(help_text='The <Data Center> is the data center, organization, or institution responsible for distributing the data.', related_name='data_center_provider', to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='data_set_language',
            field=models.CharField(blank=True, default='English', help_text='DEFAULT=English', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='metadata_name',
            field=models.CharField(default='CEOS IDN DIF', help_text='DEFAULT=CEOS IDN DIF', max_length=255),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='metadata_version',
            field=models.CharField(default='VERSION 9.9', help_text='DEFAULT=VERSION 9.9', max_length=80),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='originating_center',
            field=models.ForeignKey(blank=True, help_text='The data center or data producer who originally generated the dataset.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originating_centre_provider', to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rucontenttype',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='temporalresolutionrange',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verticalresolutionrange',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='idnnode',
            unique_together=set([('idn_node_short_name', 'idn_node_use_description', 'idn_node_long_name')]),
        ),
    ]
