# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20170215_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialcoverage',
            name='easternmost_longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees. A minus sign, "-", placed immediately before the longitude value indicates a longitude west of the Prime Meridian (defined as 0 degrees).', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='maximum_altitude',
            field=models.FloatField(blank=True, help_text='Units must be specified.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='maximum_depth',
            field=models.FloatField(blank=True, help_text='Units must be specified.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='minimum_altitude',
            field=models.FloatField(blank=True, help_text='Units must be specified.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='minimum_depth',
            field=models.FloatField(blank=True, help_text='Units must be specified.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='northernmost_latitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees. A minus sign, "-", placed immediately before the latitude value indicates a latitude south of the Equator (defined as 0 degrees latitude)', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='southernmost_latitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees. A minus sign, "-", placed immediately before the latitude value indicates a latitude south of the Equator (defined as 0 degrees latitude)', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='westernmost_longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees. A minus sign, "-", placed immediately before the longitude value indicates a longitude west of the Prime Meridian (defined as 0 degrees).', null=True),
        ),
    ]
