# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20170215_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataentry',
            name='source_name',
            field=models.ManyToManyField(blank=True, default=metadata.models.metadata_entry_platform_defaults, to='metadata.Platform'),
        ),
    ]
