# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20170215_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataentry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='dataset_publisher',
            field=models.ForeignKey(blank=True, default=metadata.models.data_set_citation_publisher_default, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='other_citation_details',
            field=models.CharField(blank=True, help_text='Additional free-text citation information. Put here about other grants and acknowledgements.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='fees',
            field=models.CharField(blank=True, default='No cost', help_text='Cost of <Distribution_Media> or distribution costs if any. Specify if there are no costs.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='data_center',
            field=models.ManyToManyField(default=metadata.models.metadata_entry_data_center_defaults, help_text='The <Data Center> is the data center, organization, or institution responsible for distributing the data.', related_name='data_center_provider', to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='idn_node',
            field=models.ManyToManyField(default=metadata.models.metadata_entry_idn_node_defaults, to='metadata.IdnNode'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='project',
            field=models.ManyToManyField(blank=True, default=[1736], to='metadata.Project'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='abstract',
            field=models.TextField(help_text='Lineage statement.'),
        ),
    ]
