# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20170215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataentry',
            name='directory',
            field=models.ManyToManyField(blank=True, to='data_storage_management.Item'),
        ),
    ]
