# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20170215_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
    ]
