# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_auto_20170215_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
