# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_auto_20170215_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataentry',
            name='data_set_citation',
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='data_set_citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.DataSetCitation'),
        ),
    ]
