# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_auto_20170216_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataentry',
            old_name='ace_project',
            new_name='expedition_project',
        ),
    ]
