# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20170219_1419'),
        ('metadata', '0015_auto_20170216_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcitation',
            name='dataset_creator',
            field=models.ManyToManyField(blank=True, to='main.Person'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='entry_title',
            field=models.CharField(help_text='Title of the data set described by the metadata. For example, <Entry_Title>......collected in the Southern Ocean during the austral summer (January - February 2017) as part of the Antarctic Circumnavigation Experiment (ACE; leg 2 of 3). </Entry_Title> provides an adequate amount of information to guide the user.', max_length=220),
        ),
#        migrations.AlterUniqueTogether(
#            name='datasetcitation',
#            unique_together=set([]),
#        ),
        migrations.RemoveField(
            model_name='datasetcitation',
            name='dataset_creator',
        ),
    ]
