# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_datasetcitation_dataset_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataentry',
            name='parent_dif',
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='parent_difs',
            field=models.ManyToManyField(blank=True, related_name='parent_difs_accessor', to='metadata.MetadataEntry'),
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='related_difs',
            field=models.ManyToManyField(blank=True, related_name='related_difs_accessor', to='metadata.MetadataEntry'),
        ),
    ]
