# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20170303_1814'),
        ('metadata', '0022_metadataentry_skip_update_distribution_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataentry',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='metadataentry',
            name='expedition_specific_device',
        ),
        migrations.RemoveField(
            model_name='metadataentry',
            name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='metadataentry',
            name='source_name',
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='sampling_methods',
            field=models.ManyToManyField(blank=True, to='main.SamplingMethod'),
        ),
    ]
