# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_auto_20170305_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialcoverage',
            name='maximum_altitude',
            field=models.FloatField(blank=True, help_text='In meters.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='maximum_depth',
            field=models.FloatField(blank=True, help_text='In meters.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='minimum_altitude',
            field=models.FloatField(blank=True, help_text='In meters.', null=True),
        ),
        migrations.AlterField(
            model_name='spatialcoverage',
            name='minimum_depth',
            field=models.FloatField(blank=True, help_text='In meters.', null=True),
        ),
    ]
