# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_auto_20170305_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataentry',
            name='data_center',
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='data_centers',
            field=models.ManyToManyField(default=metadata.models.metadata_entry_data_center_defaults, help_text='The <Data Center> is the data center, organization, or institution responsible for distributing the data.', related_name='data_center_provider', to='metadata.DataCenter'),
        ),
    ]
