# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-08-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_auto_20170306_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcitation',
            name='dataset_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Provider'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='data_centers',
            field=models.ManyToManyField(help_text='The <Data Center> is the data center, organization, or institution responsible for distributing the data.', related_name='data_center_provider', to='metadata.DataCenter'),
        ),
    ]
